name: Build

on:
    workflow_run:
        workflows: ["Test"]
        types:
            - completed

concurrency:
    group: production
    cancel-in-progress: true

jobs:
    build:
        if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main' }}

        runs-on: ubuntu-latest

        steps:
            - name: Check out the code
              uses: actions/checkout@v4

            - name: Build the Docker image
              run: docker build --file Dockerfile --tag ghcr.io/jamie6king/skycast:latest .

            - name: Upload the Docker image
              run: |
                  echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username jamie6king --password-stdin
                  docker push ghcr.io/jamie6king/skycast:latest
