name: Test

on: push

jobs:
  
  test:

    runs-on: ubuntu-latest

    steps:

      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Install dependencies
        run: |
               npm i
               npx playwright install --with-deps

      - name: Run tests
        env:
          - API_KEY=${{ secrets.API_KEY }}
        run: npm run test

      - name: Test ESLint
        run: npx eslint